// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGtd3WXplVT4Qny-pBSPJkoTysLEny7KQ',
    appId: '1:675341167228:web:01fdeba0dbb1f39e5d77f9',
    messagingSenderId: '675341167228',
    projectId: 'opti-job',
    authDomain: 'opti-job.firebaseapp.com',
    storageBucket: 'opti-job.firebasestorage.app',
    measurementId: 'G-HGZL5WTRH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgMYUpMqX9N0eq0DBMryl-tZuC_COTY-I',
    appId: '1:675341167228:android:bbb3c3e3617a275d5d77f9',
    messagingSenderId: '675341167228',
    projectId: 'opti-job',
    storageBucket: 'opti-job.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBFydi3iTB7w6RarGXPNKlgDuuiKEQ0dM',
    appId: '1:675341167228:ios:732c3247292d5ded5d77f9',
    messagingSenderId: '675341167228',
    projectId: 'opti-job',
    storageBucket: 'opti-job.firebasestorage.app',
    iosBundleId: 'com.example.infojobsFlutterApp',
  );
}
